In [ ]:
pip install numpy

In [2]:
import numpy as np

In [2]:
np.__version__

'1.24.4'

# Speed Test: Python vs. Numpy

In [3]:
num = 20000000

In [4]:
%%time 
list_1 = [i for i in range(num)]
list_2 = [j for j in range(num)]
for i in range(num):
    list_1[i] + list_2[i]

Wall time: 10.9 s


In [5]:
%%time
arr_1 = np.arange(num)
arr_2 = np.arange(num)
arr_1 + arr_2

Wall time: 94.2 ms


array([       0,        2,        4, ..., 39999994, 39999996, 39999998])

# array

In [7]:
A = np.array( [1,2,3] )
A

array([1, 2, 3])

In [8]:
type(A)

numpy.ndarray

In [9]:
A.ndim

1

In [10]:
A.shape

(3,)

In [11]:
A.size

3

In [12]:
B = np.array( [ [11,12,13],[22,23,24],[33,34,35] ] )
B

array([[11, 12, 13],
       [22, 23, 24],
       [33, 34, 35]])

In [13]:
type(B)

numpy.ndarray

In [14]:
B.ndim

2

In [15]:
B.shape

(3, 3)

In [16]:
B.size

9

In [17]:
C = np.array([[[[42,65],[82,34],[75,27]],[[12,63],[42,64],[45,87]]], 
             [[[33,43],[35,37],[21,53]],[[14,43],[53,75],[68,23]]],
             [[[42,65],[82,34],[75,27]],[[12,63],[42,64],[45,87]]]])
C

array([[[[42, 65],
         [82, 34],
         [75, 27]],

        [[12, 63],
         [42, 64],
         [45, 87]]],


       [[[33, 43],
         [35, 37],
         [21, 53]],

        [[14, 43],
         [53, 75],
         [68, 23]]],


       [[[42, 65],
         [82, 34],
         [75, 27]],

        [[12, 63],
         [42, 64],
         [45, 87]]]])

In [18]:
type(C)

numpy.ndarray

In [19]:
C.ndim

4

In [20]:
C.shape

(3, 2, 3, 2)

In [21]:
C.size

36

### random

In [22]:
np.random.randint(5)

2

In [23]:
np.random.randint(5,15, (3))

array([5, 7, 8])

In [24]:
np.random.randint(10,100, [3,2,3,2])

array([[[[77, 69],
         [63, 16],
         [99, 46]],

        [[94, 45],
         [45, 23],
         [25, 66]]],


       [[[79, 20],
         [54, 19],
         [77, 39]],

        [[40, 30],
         [40, 68],
         [79, 53]]],


       [[[63, 40],
         [68, 15],
         [17, 98]],

        [[98, 42],
         [13, 16],
         [92, 43]]]])

In [25]:
np.random.rand(2)

array([0.07496681, 0.33475646])

In [26]:
10*np.random.rand(2)

array([2.01328525, 1.92151948])

arange

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(5,7)

array([5, 6])

In [29]:
np.arange(10,20,5)

array([10, 15])

In [30]:
D = np.arange(10,40,2)
D

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [31]:
D[3]

16

In [32]:
D[-1]

38

In [33]:
D[-3:-1] #***

array([34, 36])

In [34]:
D[-3:]

array([34, 36, 38])

In [35]:
D[0]=11
D

array([11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [36]:
D[1:4] = 12,13,14
D

array([11, 12, 13, 14, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

reshape

In [37]:
D

array([11, 12, 13, 14, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [38]:
D.size

15

In [39]:
E = D.reshape(3,5)
E

array([[11, 12, 13, 14, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [40]:
E.shape

(3, 5)

In [41]:
E.ndim

2

In [42]:
E[1]

array([20, 22, 24, 26, 28])

In [43]:
E[1][2]

24

In [44]:
E[1,2]

24

In [45]:
E

array([[11, 12, 13, 14, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [46]:
# مربع سمت راست پایین را میخواهیم:

In [47]:
E[-2: , -2:]

array([[26, 28],
       [36, 38]])

In [48]:
# فقط سطر اول و آخر رو میخوایم:

In [54]:
E[[0,-1], :]

array([[11, 12, 13, 14, 18],
       [30, 32, 34, 36, 38]])

In [50]:
# فقط ستون اول و آخر رو میخوایم:

In [51]:
E[:, [0, -1]]

array([[11, 18],
       [20, 28],
       [30, 38]])

In [56]:
F = np.arange(1,18,3).reshape(3,2)
F[[1]]

array([[ 7, 10]])

linspace

In [5]:
np.linspace(2,18)

array([ 2.        ,  2.32653061,  2.65306122,  2.97959184,  3.30612245,
        3.63265306,  3.95918367,  4.28571429,  4.6122449 ,  4.93877551,
        5.26530612,  5.59183673,  5.91836735,  6.24489796,  6.57142857,
        6.89795918,  7.2244898 ,  7.55102041,  7.87755102,  8.20408163,
        8.53061224,  8.85714286,  9.18367347,  9.51020408,  9.83673469,
       10.16326531, 10.48979592, 10.81632653, 11.14285714, 11.46938776,
       11.79591837, 12.12244898, 12.44897959, 12.7755102 , 13.10204082,
       13.42857143, 13.75510204, 14.08163265, 14.40816327, 14.73469388,
       15.06122449, 15.3877551 , 15.71428571, 16.04081633, 16.36734694,
       16.69387755, 17.02040816, 17.34693878, 17.67346939, 18.        ])

In [6]:
np.linspace(1,10,num=10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [58]:
np.linspace(1,10,10, endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [11]:
len(np.linspace(5,25,15))

15

In [15]:
np.linspace(5,25,15).reshape(5,3)

array([[ 5.        ,  6.42857143,  7.85714286],
       [ 9.28571429, 10.71428571, 12.14285714],
       [13.57142857, 15.        , 16.42857143],
       [17.85714286, 19.28571429, 20.71428571],
       [22.14285714, 23.57142857, 25.        ]])

astype , dtype

In [17]:
F = np.array([ [10,15],
               [20,25]
             ]).astype(np.float32)
F

array([[10., 15.],
       [20., 25.]], dtype=float32)

In [18]:
F.dtype

dtype('float32')

In [21]:
H = F.astype(np.int32)
H

array([[10, 15],
       [20, 25]])

In [22]:
H.dtype

dtype('int32')

ones , zeros , ...

In [35]:
AA = np.zeros(3)
AA

array([0., 0., 0.])

In [38]:
AB = np.zeros((2,3))
AB

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
AC = np.zeros((2,2,2), dtype=np.int32)
AC

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [25]:
BA = np.ones(5)
BA

array([1., 1., 1., 1., 1.])

In [27]:
BB = np.ones((3,3), dtype=np.int32)
BB

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
BC = np.ones((2,3,3), dtype=np.float32)
BC

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.eye(2,3, dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0]])

In [48]:
np.full([3,3],8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [50]:
np.full([3,3,2],13)

array([[[13, 13],
        [13, 13],
        [13, 13]],

       [[13, 13],
        [13, 13],
        [13, 13]],

       [[13, 13],
        [13, 13],
        [13, 13]]])

diag :

In [51]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [52]:
np.diag([5,0,5,0,5])

array([[5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5]])

triu , tril

In [63]:
M = np.arange(1,10).reshape(3,3)

In [68]:
np.triu(M)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [69]:
np.triu(M, k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [70]:
np.triu(M, k=2)

array([[0, 0, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [65]:
np.tril(M)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [75]:
np.identity(3, dtype=np.int32) # identity just has one parameter

#  with eye the diagonal can may be offset,
#  whereas identity only fills the main diagonal


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [72]:
np.identity(2,3)

TypeError: Cannot interpret '3' as a data type

In [76]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

RANDOM - choice

In [119]:
np.random.choice(2,3) # first parameter : range of number (0 ta n-1)
                        # second parameter : size (how many number)

array([1, 0, 0])

In [120]:
np.random.choice(10,3)

array([0, 5, 1])

In [124]:
np.random.choice(2,(3,4))

array([[0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0]])

In [122]:
np.random.choice(5,5, replace=False)

array([2, 3, 0, 1, 4])

In [4]:
array_1 = np.array([1,5,10,15,20,25,30])
np.random.choice(array_1, 2, replace=False)

array([30, 10])

In [5]:
np.random.choice(array_1, (2,2), replace=False)

array([[10, 15],
       [20,  5]])

seed

In [6]:
np.random.seed(1) # stable situaton 
np.random.choice(array_1, (2,2), replace=False)

array([[30, 10],
       [ 5,  1]])

ADD , SUBTRACT , DIVIDE , ...

In [139]:
arr_1 = np.array([1,2,3,4])
arr_2 = np.array([3,4,5,6,])

In [157]:
arr_1 + 10

array([11, 12, 13, 14])

In [140]:
arr_1 + arr_2

array([ 4,  6,  8, 10])

In [141]:
np.add(arr_1 , arr_2)

array([ 4,  6,  8, 10])

In [142]:
arr_1 - arr_2

array([-2, -2, -2, -2])

In [143]:
np.subtract(arr_1 , arr_2)

array([-2, -2, -2, -2])

In [144]:
abs(np.subtract(arr_1 , arr_2))

array([2, 2, 2, 2])

In [145]:
arr_1 * arr_2

array([ 3,  8, 15, 24])

In [147]:
arr_2 / arr_1

array([3.        , 2.        , 1.66666667, 1.5       ])

In [148]:
np.divide(arr_2, arr_1)

array([3.        , 2.        , 1.66666667, 1.5       ])

In [151]:
arr_2 // arr_1

array([3, 2, 1, 1], dtype=int32)

In [153]:
arr_2 % arr_1

array([0, 0, 2, 2], dtype=int32)

In [154]:
np.divmod(arr_2,arr_1)

(array([3, 2, 1, 1], dtype=int32), array([0, 0, 2, 2], dtype=int32))

In [155]:
arr_1 ** arr_2

array([   1,   16,  243, 4096], dtype=int32)

In [156]:
np.power(arr_1 , arr_2)

array([   1,   16,  243, 4096], dtype=int32)

In [158]:
# in two dims:

In [59]:
np.random.seed(1)
a1 = np.random.randint(1,10, [3,3])
a2 = np.random.randint(1,10, [3,3])

In [60]:
a1

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [167]:
a2

array([[5, 6, 3],
       [5, 3, 5],
       [8, 8, 2]])

In [168]:
a1 + a2

array([[11, 15,  9],
       [ 6,  4,  7],
       [16, 15,  5]])

In [169]:
a1

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [170]:
np.min(a1)

1

In [171]:
np.max(a1)

9

In [172]:
np.argmin(a1)

3

In [173]:
np.argmax(a1)

1

In [201]:
np.min(a1, axis=0) # دید ستونی

array([1, 1, 2])

In [203]:
np.min(a1, axis=1) # دید سطری

array([6, 1, 3])

In [204]:
np.argmin(a1, axis=0)

array([1, 1, 1], dtype=int64)

In [210]:
np.argmin(a1, axis=1)

array([0, 0, 2], dtype=int64)

In [212]:
a1

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [214]:
np.argmax(a1, axis=0)

array([2, 0, 0], dtype=int64)

In [207]:
np.sort(a1)

array([[6, 6, 9],
       [1, 1, 2],
       [3, 7, 8]])

In [62]:
np.sort(a1, axis=1)

array([[6, 6, 9],
       [1, 1, 2],
       [3, 7, 8]])

In [209]:
np.sort(a1, axis=0)

array([[1, 1, 2],
       [6, 7, 3],
       [8, 9, 6]])

In [218]:
a1

array([[6, 9, 6],
       [1, 1, 2],
       [8, 7, 3]])

In [219]:
np.sum(a1)

43

In [220]:
np.sum(a1, axis=0)

array([15, 17, 11])

In [221]:
np.sum(a1, axis=1)

array([21,  4, 18])

In [176]:
np.sin(0)

0.0

In [181]:
np.cos(np.pi)

-1.0

In [182]:
np.tan(0)

0.0

In [186]:
b1 = [2,4,5,6]

In [187]:
np.average(b1)

4.25

In [188]:
np.sum(b1)/len(b1)

4.25

In [189]:
np.cumsum(b1)

array([ 2,  6, 11, 17], dtype=int32)

In [192]:
np.cumprod(b1)

array([  2,   8,  40, 240], dtype=int32)

In [195]:
np.std(b1)

1.479019945774904

In [199]:
np.var(b1) == np.std(b1)**2

True

In [63]:
??np