In [1]:
import numpy as np

In [2]:
A = np.array([2,4,5,6,7])
A

array([2, 4, 5, 6, 7])

In [3]:
A < 5

array([ True,  True, False, False, False])

In [6]:
A >= 3

array([False,  True,  True,  True,  True])

In [4]:
A == 5

array([False, False,  True, False, False])

In [5]:
A % 2 == 0

array([ True,  True, False,  True, False])

In [7]:
A[A > 4] # خود اعداد رو برمیگردونه

array([5, 6, 7])

In [8]:
A[A % 2 ==0]

array([2, 4, 6])

In [9]:
mask= [True, True, False, False, True]

In [10]:
A[mask]

array([2, 4, 7])

ALL , ANY

In [11]:
A

array([2, 4, 5, 6, 7])

In [16]:
all(A==2) # built-in function

False

In [15]:
any(A==2)

True

In [18]:
np.all(A==2) # Numpy

False

In [19]:
np.any(A==2)

True

In [36]:
B = np.array( [
    [2,4,4],
    [3,2,6],
])
B

array([[2, 4, 4],
       [3, 2, 6]])

In [37]:
np.all(B <= 5)

False

In [38]:
np.all(B <=5 , axis=0)

array([ True,  True, False])

In [39]:
np.all(B <=5 , axis=1)

array([ True, False])

In [40]:
np.all(B[:,:2] <= 5)

True

In [41]:
B[:,:2]

array([[2, 4],
       [3, 2]])

In [42]:
B

array([[2, 4, 4],
       [3, 2, 6]])

In [43]:
np.any(B % 2 ==0)

True

In [44]:
np.any(B % 3 ==0 , axis=0)

array([ True, False,  True])

In [45]:
np.any(B % 3 ==0 , axis=1)

array([False,  True])

Logical Operators

In [46]:
np.logical_and(True, False)

False

In [47]:
np.logical_and(True, True)

True

In [48]:
np.logical_or(True, False)

True

In [49]:
np.logical_or(False, False)

False

In [50]:
np.logical_not(False)

True

In [51]:
np.logical_not(True)

False

In [56]:
np.logical_xor(True,True) # XOR : فرد تا صحیح یا ترو

False

In [53]:
np.logical_xor(True,False)

True

In [54]:
np.logical_xor(False,True)

True

In [55]:
np.logical_xor(False,False)

False

In [59]:
B

array([[2, 4, 4],
       [3, 2, 6]])

In [60]:
mask1 = B>=4
mask1

array([[False,  True,  True],
       [False, False,  True]])

In [61]:
mask2 = B%2==0
mask2

array([[ True,  True,  True],
       [False,  True,  True]])

In [62]:
np.logical_and(mask1,mask2)

array([[False,  True,  True],
       [False, False,  True]])

In [64]:
B[np.logical_and(mask1,mask2)]

array([4, 4, 6])

In [65]:
np.logical_or(mask1,mask2)

array([[ True,  True,  True],
       [False,  True,  True]])

In [66]:
B[np.logical_or(mask1,mask2)]

array([2, 4, 4, 2, 6])

In [70]:
B

array([[2, 4, 4],
       [3, 2, 6]])

In [67]:
B1 = B
B1

array([[2, 4, 4],
       [3, 2, 6]])

In [68]:
B1 is B

True

In [69]:
B2 = B.copy()
B2

array([[2, 4, 4],
       [3, 2, 6]])

In [71]:
B2 is B

False