In [1]:
import numpy as np

VSTACK , ROW_STACK , HSTACK , COLUMN_STACK ,
CONCATENATE

In [2]:
A = np.random.randint(10,100, size=(2,3))
A

array([[23, 51, 96],
       [26, 99, 71]])

In [3]:
B = np.random.randint(10,100, size=(2,3))
B

array([[88, 79, 97],
       [49, 28, 62]])

In [4]:
np.vstack((A,B))

array([[23, 51, 96],
       [26, 99, 71],
       [88, 79, 97],
       [49, 28, 62]])

In [5]:
np.row_stack((A,B))

array([[23, 51, 96],
       [26, 99, 71],
       [88, 79, 97],
       [49, 28, 62]])

In [6]:
np.all( np.vstack((A,B)) == np.row_stack((A,B)) )

True

In [7]:
np.hstack((A,B))

array([[23, 51, 96, 88, 79, 97],
       [26, 99, 71, 49, 28, 62]])

In [8]:
np.column_stack((A,B))

array([[23, 51, 96, 88, 79, 97],
       [26, 99, 71, 49, 28, 62]])

In [9]:
np.all( np.hstack((A,B)) == np.column_stack((A,B)) )

True

In [10]:
np.concatenate((A,B))

array([[23, 51, 96],
       [26, 99, 71],
       [88, 79, 97],
       [49, 28, 62]])

In [11]:
np.all( np.vstack((A,B)) == np.concatenate((A,B)) )

True

In [12]:
np.concatenate((A,B), axis=1)

array([[23, 51, 96, 88, 79, 97],
       [26, 99, 71, 49, 28, 62]])

In [13]:
np.all( np.hstack((A,B)) == np.concatenate((A,B), axis=1))

True

In [14]:
A = np.random.randint(10,100,(3,4))
A

array([[86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [15]:
B = np.random.randint(10,100,(3,4))
B

array([[93, 13, 99, 22],
       [52, 95, 21, 60],
       [98, 20, 91, 21]])

In [16]:
np.stack((A,B))

array([[[86, 25, 39, 81],
        [18, 35, 49, 87],
        [81, 65, 46, 52]],

       [[93, 13, 99, 22],
        [52, 95, 21, 60],
        [98, 20, 91, 21]]])

In [17]:
np.stack((A,B), axis=1)

array([[[86, 25, 39, 81],
        [93, 13, 99, 22]],

       [[18, 35, 49, 87],
        [52, 95, 21, 60]],

       [[81, 65, 46, 52],
        [98, 20, 91, 21]]])

In [18]:
c = np.stack((A,B), axis=1)
c.shape

(3, 2, 4)

In [19]:
A

array([[86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [20]:
B

array([[93, 13, 99, 22],
       [52, 95, 21, 60],
       [98, 20, 91, 21]])

In [21]:
np.stack((A,B), axis=2)

array([[[86, 93],
        [25, 13],
        [39, 99],
        [81, 22]],

       [[18, 52],
        [35, 95],
        [49, 21],
        [87, 60]],

       [[81, 98],
        [65, 20],
        [46, 91],
        [52, 21]]])

In [22]:
d = np.stack((A,B), axis=2)
d.shape

(3, 4, 2)

In [23]:
A

array([[86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [24]:
np.insert(A, 0, 10) # 10 mire too index e 0

array([10, 86, 25, 39, 81, 18, 35, 49, 87, 81, 65, 46, 52])

In [25]:
np.insert(A, 0, 10, axis=0)

array([[10, 10, 10, 10],
       [86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [26]:
np.insert(A, 0, 10, axis=1)

array([[10, 86, 25, 39, 81],
       [10, 18, 35, 49, 87],
       [10, 81, 65, 46, 52]])

In [27]:
np.insert(A, [0,1], 10, axis=0)

array([[10, 10, 10, 10],
       [86, 25, 39, 81],
       [10, 10, 10, 10],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [28]:
np.insert(A, (0,1), 10, axis=0)

array([[10, 10, 10, 10],
       [86, 25, 39, 81],
       [10, 10, 10, 10],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [29]:
np.insert(A, [0,3], 10, axis=0)

array([[10, 10, 10, 10],
       [86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52],
       [10, 10, 10, 10]])

In [30]:
np.insert(A, [0,4], 10, axis=1)

array([[10, 86, 25, 39, 81, 10],
       [10, 18, 35, 49, 87, 10],
       [10, 81, 65, 46, 52, 10]])

In [31]:
np.insert(A, [0,1], 10, axis=1)

array([[10, 86, 10, 25, 39, 81],
       [10, 18, 10, 35, 49, 87],
       [10, 81, 10, 65, 46, 52]])

In [32]:
np.insert(A, 0, (10,20,30), axis=1)

array([[10, 86, 25, 39, 81],
       [20, 18, 35, 49, 87],
       [30, 81, 65, 46, 52]])

In [33]:
A

array([[86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [34]:
mask1 = np.full([3,3],10)

In [35]:
np.concatenate((mask1,A), axis=1)

array([[10, 10, 10, 86, 25, 39, 81],
       [10, 10, 10, 18, 35, 49, 87],
       [10, 10, 10, 81, 65, 46, 52]])

In [36]:
mask2 = np.full([2,4],10)
np.concatenate((mask2,A), axis=0)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

Delete

In [37]:
B

array([[93, 13, 99, 22],
       [52, 95, 21, 60],
       [98, 20, 91, 21]])

In [38]:
np.delete(B, 1, axis=0)

array([[93, 13, 99, 22],
       [98, 20, 91, 21]])

In [39]:
np.delete(B, 0, axis=1)

array([[13, 99, 22],
       [95, 21, 60],
       [20, 91, 21]])

In [40]:
c = np.delete(B, 1 , axis=0)
d = B[1]
np.insert(c, 1, d, axis=0)

array([[93, 13, 99, 22],
       [52, 95, 21, 60],
       [98, 20, 91, 21]])

In [41]:
e = np.insert(c, 1, d, axis=0)
np.all( B == e )

True

In [42]:
Q = np.random.randint(10,100, (2,3,4))
Q

array([[[42, 65, 91, 12],
        [35, 40, 88, 12],
        [29, 51, 88, 46]],

       [[26, 55, 16, 87],
        [89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [43]:
np.delete(Q, 0 , axis=0)

array([[[26, 55, 16, 87],
        [89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [44]:
np.delete(Q, 0 , axis=1)

array([[[35, 40, 88, 12],
        [29, 51, 88, 46]],

       [[89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [45]:
np.delete(Q, 0 , axis=2)

array([[[65, 91, 12],
        [40, 88, 12],
        [51, 88, 46]],

       [[55, 16, 87],
        [46, 55, 82],
        [75, 64, 14]]])

APPEND

In [46]:
W = np.append(Q, [10,11,12])
print(W)
print(f'shape : {W.shape}')

[42 65 91 12 35 40 88 12 29 51 88 46 26 55 16 87 89 46 55 82 76 75 64 14
 10 11 12]
shape : (27,)


In [47]:
W.reshape(3,9)

array([[42, 65, 91, 12, 35, 40, 88, 12, 29],
       [51, 88, 46, 26, 55, 16, 87, 89, 46],
       [55, 82, 76, 75, 64, 14, 10, 11, 12]])

In [48]:
Q

array([[[42, 65, 91, 12],
        [35, 40, 88, 12],
        [29, 51, 88, 46]],

       [[26, 55, 16, 87],
        [89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [49]:
i = np.random.randint(10,100, (2,3))
j = np.random.randint(10,100, (2,3))
print(i ,"\n" , "\n" , j)

[[31 70 67]
 [56 16 63]] 
 
 [[12 41 28]
 [61 91 74]]


In [50]:
np.append(i, j, axis=0)

array([[31, 70, 67],
       [56, 16, 63],
       [12, 41, 28],
       [61, 91, 74]])

In [51]:
np.append(i, j, axis=1)

array([[31, 70, 67, 12, 41, 28],
       [56, 16, 63, 61, 91, 74]])

In [52]:
i

array([[31, 70, 67],
       [56, 16, 63]])

In [53]:
np.tile(i, 2)

array([[31, 70, 67, 31, 70, 67],
       [56, 16, 63, 56, 16, 63]])

In [54]:
np.tile(i, (2,2))

array([[31, 70, 67, 31, 70, 67],
       [56, 16, 63, 56, 16, 63],
       [31, 70, 67, 31, 70, 67],
       [56, 16, 63, 56, 16, 63]])

In [55]:
i

array([[31, 70, 67],
       [56, 16, 63]])

In [56]:
np.repeat(i, 2)

array([31, 31, 70, 70, 67, 67, 56, 56, 16, 16, 63, 63])

In [57]:
np.repeat(i, 2).reshape(2,6)

array([[31, 31, 70, 70, 67, 67],
       [56, 56, 16, 16, 63, 63]])

In [58]:
np.repeat(i,2, axis=1)

array([[31, 31, 70, 70, 67, 67],
       [56, 56, 16, 16, 63, 63]])

In [59]:
np.repeat(i,3, axis=0)

array([[31, 70, 67],
       [31, 70, 67],
       [31, 70, 67],
       [56, 16, 63],
       [56, 16, 63],
       [56, 16, 63]])

In [60]:
x = np.repeat(i,3, axis=0)
x.flatten() 

array([31, 70, 67, 31, 70, 67, 31, 70, 67, 56, 16, 63, 56, 16, 63, 56, 16,
       63])

SPLIT

In [61]:
Q

array([[[42, 65, 91, 12],
        [35, 40, 88, 12],
        [29, 51, 88, 46]],

       [[26, 55, 16, 87],
        [89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [62]:
np.split(Q,1,axis=0)

[array([[[42, 65, 91, 12],
         [35, 40, 88, 12],
         [29, 51, 88, 46]],
 
        [[26, 55, 16, 87],
         [89, 46, 55, 82],
         [76, 75, 64, 14]]])]

In [63]:
type(np.split(Q,1,axis=0))

list

In [64]:
np.split(Q,2,axis=0)

[array([[[42, 65, 91, 12],
         [35, 40, 88, 12],
         [29, 51, 88, 46]]]),
 array([[[26, 55, 16, 87],
         [89, 46, 55, 82],
         [76, 75, 64, 14]]])]

In [65]:
np.split(Q,3,axis=1)

[array([[[42, 65, 91, 12]],
 
        [[26, 55, 16, 87]]]),
 array([[[35, 40, 88, 12]],
 
        [[89, 46, 55, 82]]]),
 array([[[29, 51, 88, 46]],
 
        [[76, 75, 64, 14]]])]

SWAPAXES

In [66]:
A

array([[86, 25, 39, 81],
       [18, 35, 49, 87],
       [81, 65, 46, 52]])

In [67]:
np.swapaxes(A,0,1)

array([[86, 18, 81],
       [25, 35, 65],
       [39, 49, 46],
       [81, 87, 52]])

In [68]:
np.transpose(A)

array([[86, 18, 81],
       [25, 35, 65],
       [39, 49, 46],
       [81, 87, 52]])

In [69]:
np.all( np.swapaxes(A,0,1) == np.transpose(A) )

True

In [70]:
Q

array([[[42, 65, 91, 12],
        [35, 40, 88, 12],
        [29, 51, 88, 46]],

       [[26, 55, 16, 87],
        [89, 46, 55, 82],
        [76, 75, 64, 14]]])

In [71]:
np.swapaxes(Q, 1,2)

array([[[42, 35, 29],
        [65, 40, 51],
        [91, 88, 88],
        [12, 12, 46]],

       [[26, 89, 76],
        [55, 46, 75],
        [16, 55, 64],
        [87, 82, 14]]])

In [72]:
np.swapaxes(Q, 0,2)

array([[[42, 26],
        [35, 89],
        [29, 76]],

       [[65, 55],
        [40, 46],
        [51, 75]],

       [[91, 16],
        [88, 55],
        [88, 64]],

       [[12, 87],
        [12, 82],
        [46, 14]]])

In [73]:
Q.shape

(2, 3, 4)

In [74]:
np.swapaxes(Q, 1,2).shape

(2, 4, 3)

In [75]:
np.swapaxes(Q, 0,2).shape

(4, 3, 2)